### ISSUE TITLE
No longer works on Dagger 2.20

### ISSUE THREAD

**Issue by spencergriffin** [hijamoya/Android-Kotlin-Dagger2-Conductor-Example#1]
I am getting the following error on Dagger 2.20:

```Caused by: java.lang.IllegalArgumentException: No injector factory bound for Class<com.hijamoya.example.ui.controller.HomeController>
        at dagger.android.DispatchingAndroidInjector.inject(DispatchingAndroidInjector.java:136)
        at com.hijamoya.example.dagger.injection.ConductorInjection$Companion.inject(ConductorInjection.kt:17)
        at com.hijamoya.example.ui.controller.BaseController.onCreateView(BaseController.kt:34)
        at com.bluelinelabs.conductor.Controller.inflate(Controller.java:988)
        at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:190)
        at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:154)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:774)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:744)
        at com.bluelinelabs.conductor.Router.setBackstack(Router.java:430)
        at com.bluelinelabs.conductor.Router.setRoot(Router.java:333)
        at com.hijamoya.example.ui.MainActivity.onCreate(MainActivity.kt:29)```

**Comment by hijamoya** [comment]
Check this commit:
https://github.com/hijamoya/Android-Kotlin-Dagger2-Conductor-Example/commit/29b0f3a315880e3b5b7959e1af8a344c4864595b
I have updated to make dagger upgrade to 2.24.
